apiVersion: initkit.io/v1alpha1
kind: WorkstationProfile
metadata:
  name: developer
spec:
  target:
    os:
      distribution: fedora
  phases:
    - name: editors
      steps:
        - name: editors
          kind: dnf-packages
          spec:
            packages: [neovim, helix]

    - name: desktop
      dependsOn: [editors]
      steps:
        - name: apps
          kind: flatpak-packages
          spec:
            appIds:
              - com.github.tchx84.Flatseal
